-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "Permission" ADD VALUE 'CREATE_INSTRUCAO_COBRANCA';
ALTER TYPE "Permission" ADD VALUE 'UPDATE_INSTRUCAO_COBRANCA';
ALTER TYPE "Permission" ADD VALUE 'DELETE_INSTRUCAO_COBRANCA';
ALTER TYPE "Permission" ADD VALUE 'VIEW_INSTRUCOES_COBRANCA';
ALTER TYPE "Permission" ADD VALUE 'CREATE_INSTRUCAO_RECEBIMENTO';
ALTER TYPE "Permission" ADD VALUE 'UPDATE_INSTRUCAO_RECEBIMENTO';
ALTER TYPE "Permission" ADD VALUE 'DELETE_INSTRUCAO_RECEBIMENTO';
ALTER TYPE "Permission" ADD VALUE 'VIEW_INSTRUCOES_RECEBIMENTO';
ALTER TYPE "Permission" ADD VALUE 'CREATE_CARTEIRA_COBRANCA';
ALTER TYPE "Permission" ADD VALUE 'UPDATE_CARTEIRA_COBRANCA';
ALTER TYPE "Permission" ADD VALUE 'DELETE_CARTEIRA_COBRANCA';
ALTER TYPE "Permission" ADD VALUE 'VIEW_CARTEIRAS_COBRANCA';
ALTER TYPE "Permission" ADD VALUE 'CREATE_ESPECIE_COBRANCA';
ALTER TYPE "Permission" ADD VALUE 'UPDATE_ESPECIE_COBRANCA';
ALTER TYPE "Permission" ADD VALUE 'DELETE_ESPECIE_COBRANCA';
ALTER TYPE "Permission" ADD VALUE 'VIEW_ESPECIES_COBRANCA';
ALTER TYPE "Permission" ADD VALUE 'CREATE_BANCO';
ALTER TYPE "Permission" ADD VALUE 'UPDATE_BANCO';
ALTER TYPE "Permission" ADD VALUE 'DELETE_BANCO';
ALTER TYPE "Permission" ADD VALUE 'VIEW_BANCOS';
